project:
  type: book
  output-dir: docs
#https://quarto.org/docs/output-formats/html-themes.html
book:
  title: "CASA00023 Learning Diary"
  author: "Norah Alhosain"
  date: "1/22/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - W2_Xaringan.qmd
    - W3_Corrections.qmd
    - W4_Policy.qmd
    - W6_GEE.qmd
    - W7_classificarion_1.qmd
    - references.qmd
  search: true
  #repo-url: 
 # title-block-banner: true
 # favicon: logo.png
  sidebar:
    style: docked
    background: light



bibliography: references.bib

format:
  html:
    theme:
      - Simplex
      - brand
  pdf:
    documentclass: scrreprt
#  epub:
#   cover-image: cover.png ## remeber to add this ()

editor: visual

